### ISSUE TITLE
Where is the <leader> key set?

### ISSUE THREAD

**Issue by MathiasOdlund** [mistgc/config.nvim#2]
I love this project, I have been trying to find a prebuilt config for Colemak and this works like a charm. I was just wondering where the leader key was set. I want to change it to the spacebar.

**Comment by mistgc** [comment]
The default leader key is "\\" if you wanna change it to the spacebar, write `vim.g.mapleader = " "` into anywhere.

But I recommend you to put `vim.g.mapleader = " "` to the end of the **lua/options/opts.lua**.
And finally, don't forget to remove the line `map("n", "<space>", "viw", {})` in **lua/keymaps/local.lua**.

**Comment by MathiasOdlund** [comment]
Thank you, that worked like a charm.
